config/routes.rb
Tipster::Application.routes.draw do

  # root :to => 'lists#index'
  root :to => 'lists#index'

  mount Citygate::Engine => '/'

  resources :lists do
    resources :tips

    member do
      post :favorite
    end
  end

  resources :users do
    member do
      post :follow
    end
  end

  match '/profile' => 'users#profile'
  match '/feed' => 'feeds#main'
  match '/follows' => 'feeds#follows'
  match '/favorites' => 'feeds#favorites'


  match '/community' => 'community#show'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= Citygate::User.new

    can :read, :all

    if user.persisted?
      can :profile, Citygate::User
      can :manage, Citygate::User, id: user.id
      #can :manage, :all

      can :manage, List,   user_id: user.id
      can :manage, Follow, user_id: user.id
      #can :new, List
      can :manage, Tip, list:     { user_id: user.id }
      can :manage, :all
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  #### Relations
  has_many :lists

  #### Accessors
  attr_accessible :name

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  
  #### Relations
  belongs_to :user, :class_name => 'Citygate::User'
  belongs_to :favorited, :class_name => 'List', :foreign_key => :list_id

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  
  #### Relations
  belongs_to :user, :class_name => 'Citygate::User'
  belongs_to :followed, :class_name => 'Citygate::User'


  attr_accessible :user_id, :followed_id

end

app/models/list.rb
class List < ActiveRecord::Base
  include PublicActivity::Model
  tracked :owner => proc { |controller, model| controller.current_user },
    :params => {
      author: proc { |controller, model| model.user.name_or_email },
      time:   proc { |controller, model| model.created_at },
      title:  proc { |controller, model| model.title }
    }

  #### Relations
  belongs_to :user, :class_name => 'Citygate::User'
  has_many :tips
  belongs_to :category


  has_many :favorites
  has_many :favoriters, :through => :favorites, :source => :user, :class_name => 'Citygate::User'


  attr_accessible :category_id, :title, :desc
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  include PublicActivity::Model
  tracked :owner => proc { |controller, model| controller.current_user },
    :params => {
      author: proc { |controller, model| model.list.user.name_or_email },
      time:   proc { |controller, model| model.created_at },
      list:   proc { |controller, model| model.list.title },
      title:  proc { |controller, model| model.title }
    }

  #### Relations
  belongs_to :list
  has_many :favorites

  has_many :favorites
  has_many :favoriters, :through => :follows, :source => :user, :class_name => 'Citygate::User'

  #### Accessors
  attr_accessible :content, :title

  #### Scopes
  scope :by_list, lambda { |list| where list_id: list.id }
  scope :by_follower, lambda { |user| joins(:list => :follows).where("follows.user_id == #{user.id}").order('tips.updated_at ASC').limit(10) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController

  protect_from_forgery

  before_filter :load_user_tips

  rescue_from CanCan::AccessDenied do |exception|
    if user_signed_in?
      flash[:error] = "Please don't try to go there. Stuff would break :("
        Rails.logger.debug "Access denied on #{exception.action} #{exception.subject.inspect}"
      redirect_to profile_path
    else
      flash[:notice] = 'Please register first!'
      redirect_to citygate.new_user_session_path
    end
  end


  #protected

    def load_user_tips
      if user_signed_in?
        @user_lists = current_user.lists.where('id NOT NULL') if user_signed_in?
      end
    end

end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
  # layout 'home'
  # GET /
  def show
    @users = Citygate::User.all
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  load_and_authorize_resource class: 'Citygate::User'

  def main
    #@followed_tips = Tip.by_follower(current_user)
    @activities = PublicActivity::Activity.all
  end

  def follows
    @follows = current_user.follows
  end

  def favorites
    @user = current_user
    @favorites = current_user.favorited
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # layout 'home'
  # GET /
  def show
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  load_and_authorize_resource class: 'Citygate::User', only: [:new, :create]

  before_filter :get_list_by_id, except: [:index, :new, :create]

  # GET /lists
  def index
    if user_signed_in?
      @lists = List.where(:user_id => current_user.id)
    else
      @lists = List.all
    end
  end

  # GET /lists/1
  def show
    @list = List.find(params[:id])
  end

  # GET /lists/new
  def new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  def create
    @list = List.new(params[:list])
    @list.user_id = current_user.id

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /lists/1
  def update
    @list = List.find(params[:id])

    if @list.update_attributes(params[:list])
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render action: "edit" 
    end
  end

  # DELETE /lists/1
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to :root
  end

  def favorite
    @list.favoriters << current_user
    redirect_to favorites_path
  end


  protected

    def get_list_by_id
      @list = List.find(params[:id])
    end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController

  load_and_authorize_resource class: 'Citygate::User', only: [:new, :create]


  before_filter :load_list

  # GET /tips
  def index
    @tips = @list.tips
  end

  # GET /tips/1
  def show
    @tip = Tip.find(params[:id])
  end

  # GET /tips/new
  def new
    @tip = @list.tips.build
  end

  # GET /tips/1/edit
  def edit
    @tip = Tip.find(params[:id])
  end

  # POST /tips
  def create
    @tip = Tip.new(params[:tip])

    if @tip.save
      @list.tips << @tip
      redirect_to list_path(@tip.list), notice: 'Tip was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /tips/1
  def update
    @tip = Tip.find(params[:id])

    if @tip.update_attributes(params[:tip])
      redirect_to list_tip_url(@list), notice: 'Tip was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /tips/1
  def destroy
    @tip = Tip.find(params[:id])
    @tip.destroy
    redirect_to :root
  end


  protected

    def load_list
      @list = List.find(params[:list_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource class: 'Citygate::User'

  def profile
    authorize! :show, current_user
  end

  def show
    @user = Citygate::User.find(params[:id])

  end

  def follow
    @user = Citygate::User.find(params[:id])
    Follow.create user_id: current_user.id, followed_id: @user.id
    #@user.followers << current_user
    redirect_to follows_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_with_icon (text, destiny, imgname)
    img = image_tag imgname, :class => 'icon'
    link_to destiny do
      "<button class=\"btn\">#{img} <span class=\"icon\">#{text}</span></button>".html_safe
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/community/show.html.erb
<h3>Community</h3>


<% @users.each do |user| %>

  <div class="tip-container">
    <div class="tip-title">
    <i class='icon-caret-right'></i><%= user.first_name%>
    </div>
    <i class='icon-eye-open'></i><%= link_to "   Follow", follow_user_path(user),  method: :post  %>
    <br/>
    <i class='icon-info-sign'></i><%= link_to "    Open profile", user_path(user.id) %>
</div>
<hr/>
<% end %>

app/views/feeds/favorites.html.erb
<h3><%= current_user.first_name %>'s favorites</h3>

<%= render 'lists/table', lists: @favorites %>

app/views/feeds/follows.html.erb
<h3>Following</h3>

<% if @follows.empty? %>

This user still don't follows anyone

<% else %>

<% @follows.each do |follow| %>
  <i class="icon-caret-right"></i>
  <%= link_to follow.followed, follow.followed.first_name %>
<% end %>

<% end %>

app/views/feeds/main.html.erb
<%# @followed_tips.each do |tip| %>
  <%#= render 'tips/table', tips: @followed_tips %>
<%# end %>
<% for activity in @activities %>
  <div class="row-fluid">
    <div class="span12">
      <div class="well">
        <%= render_activity(activity, :layout => :activity) %>
        <%#= activity.text.html_safe %>
        <%#= time_ago_in_words(activity.created_at) %> ago
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<%# flash = { :notice => 'lol' } unless flash %>
<% if notice %>
  <div class="row-fluid">
    <div class="span6 offset3 alert alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= notice %>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="row-fluid">
    <div class="span6 offset3 alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= alert %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a href="/" class="logo"><%= image_tag("logo.png") %></a>


      <div class="container nav-collapse">

        <ul class="nav pull-right">

          <li>
            <div class="btn-group">
              <% if user_signed_in? %>
                  <%= link_to current_user do %>
                  <button class="btn">
                    <i class="icon-tasks"></i>
                    <%= current_user.first_name %>
                  </button>
                  <% end %>
                  <% end %>

              <% if user_signed_in? %>
                <%= link_to citygate.destroy_user_session_path, :method => :delete do %>
                  <button class="btn">
                    <%= image_tag 'glyphicons/lock.png', :class => 'icon' %>
                    Sign Out
                  </button>
                <% end %>
              <% else %>
                <%= button_with_icon 'Sign In', citygate.new_user_session_path, 'glyphicons/unlock.png' %>

                <%= button_with_icon 'Sign in with Twitter', '/users/auth/twitter', 'glyphicons/twitter.png' %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <%= render 'layouts/flash' %>
</div>

app/views/layouts/activity.html.erb
<div class="span4">
  <div class="well">
    <%= yield %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tipster" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <link rel="stylesheet" href="sticky.css" />
    <%= stylesheet_link_tag "bootstrap", :media => "all" %>
    <%= stylesheet_link_tag "bootstrap-responsive", :media => "all" %>
    <%= stylesheet_link_tag "google-prettify", :media => "all" %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%#= stylesheet_link_tag 'http://yandex.st/highlightjs/7.3/styles/default.min.css', :media => 'all' %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body data-spy="scroll" data-target=".bs-docs-sidebar">

    <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="content">

        <div class="wrapper">
          <div class="proper-content">
            <div class="row">
              <div class="span3">
                <ul class="nav nav-list">
                <li class="nav-header">dashboard</li>
                <li>
                  <%= link_to '/feed' do %>
                    <i class='icon-link'></i>
                    <span class="icon">Feed</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to '/community' do %>
                    <i class='icon-link'></i>
                    <span class="icon">Community</span>
                  <% end %>
                </li>

                <li>
                  <%= link_to '/follows' do %>
                    <i class='icon-link'></i>
                    <span class="icon">Following</span>
                  <% end %>
                </li>

                <li>
                  <%= link_to '/favorites' do %>
                    <i class='icon-link'></i>
                    <span class="icon">Favorites</span>
                  <% end %>
                </li>

              <li class="divider"></li>

              <%# if @lists.empty? %>
              <%# else %>
                <li class="nav-header">Tiplists</li>

                <% if @user_lists %>
                  <% @user_lists.each do |list| %>
                  <li>
                    <%= link_to list_path(list) do %>
                      <i class='icon-list-ul'></i>
                      <span class="icon"><%= list.title %></span>
                    <% end %>
                  </li>
                  <% end %>
                <%# end %>

                <li class="divider"></li>
                <% end %>
              <br/>
              <% if user_signed_in? %>
                <%= link_to new_list_path do %>
                  <button>
                    <i class='icon-plus'></i>
                    <span class="icon">Add tiplist</span>
                  </button>
                <% end %>
              <% end %>



              </ul>







              </div>
               <div class="span9">
                <%= yield %>
              </div>
            </div>
          </div><!-- /.proper-content -->

          <div class="push"></div>

        </div><!-- /.wrapper -->

        <div class="footer-wrapper">
          <footer></footer>
        </div>
      </div>
    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag 'application', 'bootstrap' %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <!--<%# if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <%# @list.errors.full_messages.each do |msg| %>
        <li><%#= msg %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>-->

  <div class="field">
    <%= f.label :category %>
    <%= collection_select :list, :category_id, Category.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desc, 'Description' %>
    <%= f.text_area :desc %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_row.html.erb
<tr>
  <td><%= link_to list.title, list %></td>
  <td>
    <span class="label label-inverse"><%= list.category.name %></span>
    <%= link_to list do %>
      <i class="icon-eye-open"></i>
    <% end %>

  </td>
  <% if can?(:manage, list) %>
    <td>
      <%= link_to edit_list_path(list) do %>
        <i class="icon-edit"></i>
      <% end %>
    </td>
    <td>
      <%= link_to list, :method => :delete, :data => { :confirm => 'Are you sure?' } do %>
        <i class="icon-remove"></i>
      <% end %>
    </td>
  <% else %>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  <% end %>
</tr>

app/views/lists/_table.html.erb
<%#<table class="table">
  <thead>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </thead> %>

  <% lists.each do |list| %>
    <%= render 'lists/row', :list => list %>
  <% end %>
<%#</table>%>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<div class="row-fluid">
  <div class="span6">
      <%= link_to lists_path do %>
        <i class="icon-arrow-left"></i>
        <span class="icon">Back</span>
      <% end %>
  </div>

  <div class="span6">
    <div class="pull-right">
      <button class="btn">
        <%= link_to @list do %>
          <i class="icon-eye-open"></i>
          <span class="icon">Show</span>
        <% end %>
      </button>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<% if user_signed_in? %>
  <div class="row-fluid">
    <div class="span8">
      <h3><%= current_user.first_name %>'s tiplists</h3>
    </div>

    <div class="span3 down">
      <div class="btn-group pull-right">
        <%= link_to new_list_path do %>
          <button class="btn">
            <i class="icon-plus"></i>
            <span class="icon">New List</span>
          </button>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row-fluid">
    <div class="span12">
      <h3>Latest tiplists</h3>
    </div>
  </div>
<% end %>

<%= render 'table', :lists => @lists %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<div class="row-fluid">
  <div class="span12">
      <%= link_to lists_path do %>
        <i class="icon-arrow-left"></i>
        <span class="icon">Back</span>
      <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="row-fluid">
  <div class="span6">
    <h3><%= @list.title %></h3>
  </div>

  <div class="span3 down">
    <% if can? :manage, @list %>
      <div class="btn-group pull-right">
        <%= link_to new_list_tip_path(@list) do %>
          <button class="btn">
            <i class="icon-plus"></i>
            <span class="icon">Add Tip</span>
          </button>
        <% end %>
        <%= link_to edit_list_path do %>
          <button class="btn">
            <i class="icon-edit"></i>
            <span class="icon">Edit</span>
          </button>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="span2 down">
    <div class="btn-group pull-right">
      <%= link_to favorite_list_path(@list), :method => :post do %>
        <button class="btn">
          <i class="icon-pushpin"></i>
          <span class="icon">Favorite</span>
        </button>
      <% end %>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span2">
    <span class="label label-inverse"><%= @list.category.name %></span>
  </div>
  <div class="span10">
    <p><%= @list.desc %><p>
  </div>
</div>

<div class="row-fluid">
  <div class=" fix-margins">
<br/>
<hr/>
  <% if @list.tips.empty? %>
    <p>There are no tips yet. <strong><%= link_to 'Why don\'t you add one?', new_list_tip_path(@list) %></strong></p>
  <% else %>
    <% @list.tips.each do |tips| %>
    <div class="tip-container">
      <div class="tip-title">
        <i class='icon-tasks'></i><%= tips.title%>
      </div>
      <div class="row-fluid">
        <div class="span12">
          <%= "<div class=\"#{@list.category.name.downcase}\">".html_safe %>
            <pre><code><%= tips.content %></code></pre>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

<br/>

<div class="row-fluid">
  <div class="span12">
      <%= link_to lists_path do %>
        <i class="icon-arrow-left"></i>
        <span class="icon">Back</span>
      <% end %>
  </div>
</div>

app/views/tips/_form.html.erb
<%= form_for([@list, @tip]) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tips/_row.html.erb
<tr>
  <td><%= tip.title %></td>
  <td><%= tip.content %></td>
  <td>
    <%= link_to list_tip_path(tip.list, tip) do %>
      <i class="icon-eye-open"></i>
    <% end %>
  </td>
  <% if can?(:manage, tip.list) %>
    <td>
      <%= link_to edit_list_tip_path(tip.list, tip) do %>
        <i class="icon-edit"></i>
      <% end %>
    </td>
    <td>
      <%= link_to list_tip_path(tip.list, tip), :method => :delete, :data => { :confirm => 'Are you sure?' } do %>
        <i class="icon-remove"></i>
      <% end %>
    </td>
  <% else %>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  <% end %>
</tr>

app/views/tips/_table.html.erb
<table class="table">
  <thead>
    <th>Title</th>
    <th>Content</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </thead>

  <% tips.each do |tip| %>
    <%= render 'tips/row', :tip => tip %>
  <% end %>

</table>

app/views/tips/edit.html.erb
<h1>Editing tip</h1>

<%= render 'form' %>

<div class="row-fluid">
  <div class="span6">
      <%= link_to list_tips_path(@list) do %>
        <i class="icon-arrow-left"></i>
        <span class="icon">Back</span>
      <% end %>
  </div>

  <div class="span6">
    <div class="pull-right">
      <%= link_to list_tips_path(@list) do %>
        <button class="btn">
          <i class="icon-eye-open"></i>
          <span class="icon">Show</span>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/tips/index.html.erb
<div class="row-fluid">
  <div class="span8">
    <h1><%= @list.title %></h1>
  </div>

  <div class="span4">
    <div class="btn-group pull-right">
      <%= link_to new_list_tip_path(@list) do %>
        <button class="btn">
          <i class="icon-plus"></i>
          <span class="icon">New Tip</span>
        </button>
      <% end %>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <h2>Tips</h2>
  </div>
</div>

<%= render 'table', :tips => @list.tips %>

<div class="row-fluid">
  <div class="span12">
      <%= link_to @list do %>
        <i class="icon-arrow-left"></i>
        <span class="icon">Back</span>
      <% end %>
  </div>
</div>

app/views/tips/new.html.erb
<h1>New tip</h1>

<%= render 'form' %>

<div class="row-fluid">
  <div class="span12">
      <%= link_to list_tips_path(@list) do %>
        <i class="icon-arrow-left"></i>
        <span class="icon">Back</span>
      <% end %>
  </div>
</div>

app/views/tips/show.html.erb
<div class="row-fluid">
  <div class="span6">
    <h1><%= @tip.title %></h1>
  </div>

  <div class="span4">
    <% if can? :manage, @tip.list %>
      <div class="btn-group pull-right">
        <%= link_to edit_list_tip_path(@list,@tip) do %>
          <button class="btn">
            <i class="icon-edit"></i>
            <span class="icon">Edit</span>
          </button>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="span2">
    <div class="btn-group pull-right">
      <%= link_to favorite_list_tip_path(@list,@tip) do %>
        <button class="btn">
          <i class="icon-star-empty"></i>
          <span class="icon">Favorite</span>
        </button>
      <% end %>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <%= "<div class=\"#{@list.category.name.downcase}\">".html_safe %>
      <pre><code><%= @tip.content %></code></pre>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>


<%#= link_to 'Edit', edit_list_tip_path(@list,@tip) %>
<%#= link_to 'Back', list_tips_path(@list) %>
<div class="row-fluid">
  <div class="span12">
      <%= link_to list_tips_path(@list) do %>
        <i class="icon-arrow-left"></i>
        <span class="icon">Back</span>
      <% end %>
  </div>
</div>

app/views/users/profile.html.erb
PROFILE

app/views/users/show.html.erb
<h3><%= @user.full_name %>'s profile</h3>
<i class='icon-eye-open'></i><%= link_to '    Follow', follow_user_path(@user), method: :post %>

<hr/>

<h3><%= @user.full_name %>'s tiplists</h3>

<% if @user.lists.empty? %>

This user still don't have any tiplist

<% else %>

<% @user.lists.each do |list| %>
  <i class='icon-reorder'></i><%= link_to list.title, list %>
<% end %>

<% end %>